learning_django/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [
    path('', include('polls.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    url(r'^api/polls/', include('polls.api.urls')),
]

polls/api/urls.py
from .views import QuestionAPI, ChoiceAPI
from django.conf.urls import url
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'questions', QuestionAPI, basename='user')
router.register(r'choice', ChoiceAPI, basename='user')
urlpatterns = router.urls

'''
urlpatterns = [
    #url(r'^question/(?P<pk>\d+)/$', QuestionAPI.as_view(), name='question_api'),
    url(r'^question/$', QuestionAPI.as_view({'get': 'list'}), name='question_api_add'),
    url(r'^choice/(?P<pk>\d+)/$', ChoiceAPI.as_view(), name='choice_api'),
    url(r'^choice/$', ChoiceAPIAdd.as_view(), name='choice_api_add'),
]
'''

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.LogoutUser.as_view(), name='logout'),
    path('add_question/', views.AddQuestion.as_view(), name='add_question'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/question_manipulation/', views.QuestionManipulation.as_view(), name='question_manipulation'),
    path('<int:question_id>/delete_question/', views.DeleteQuestion.as_view(), name='delete_question'),
    path('<int:question_id>/add_choice/', views.AddChoice.as_view(), name='add_choice'),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.conf import settings


class Question(models.Model):
    """
    model for questions
    """
    question_text = models.CharField(max_length=200)
    user_id = models.ForeignKey(get_user_model(),
                                blank=True,
                                null=True,
                                on_delete=models.SET_NULL)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=settings.QUESTION_RECENTLY_THRESHOLD) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    """
    model for choice for questions
    """
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    user_id = models.ForeignKey(get_user_model(),
                                blank=True,
                                null=True,
                                on_delete=models.SET_NULL)

    def __str__(self):
        return self.choice_text


class VotedOn(models.Model):
    """
    many to many relationship between user and question
    has data if user voted for choice in question
    """
    user_id = models.ForeignKey(get_user_model(),
                                blank=True,
                                null=True,
                                on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

polls/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    """
    form for registering user
    """
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)

polls/api/views.py
from rest_framework import generics, mixins
from polls.models import Question, Choice
from .serializers import QuestionSerializer, ChoiceSerializer
from rest_framework.response import Response
from rest_framework import permissions, status, viewsets, views
from django.shortcuts import get_object_or_404, render, redirect, Http404


class QuestionAPI(viewsets.ViewSet):
    def get_object(self, pk):
        try:
            return Question.objects.get(pk=pk)
        except Question.DoesNotExist:
            raise Http404

    def list(self, request):
        queryset = Question.objects.all()
        serializer = QuestionSerializer(queryset, many=True)
        return Response(serializer.data)

    def create(self, request, *args, **kwargs):
        serializer = QuestionSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)

    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object(kwargs['pk'])
        serializer = QuestionSerializer(instance=instance)
        return Response(serializer.data)

    def update(self, request, *args, **kwargs):
        instance = self.get_object(kwargs['pk'])
        serializer = QuestionSerializer(
            instance=instance,
            data=request.data,
            partial=True
        )
        serializer.is_valid(raise_exception=True)
        serializer.update(instance, request.data)
        return Response(serializer.data)

    def delete(self, request, *args, **kwargs):
        instance = Question.objects.get(pk=kwargs['pk'])
        instance.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class ChoiceAPI(viewsets.ViewSet):
    def get_object(self, pk):
        try:
            return Choice.objects.get(pk=pk)
        except Choice.DoesNotExist:
            raise Http404

    def list(self, request):
        queryset = Choice.objects.all()
        serializer = ChoiceSerializer(queryset, many=True)
        return Response(serializer.data)

    def create(self, request, *args, **kwargs):
        serializer = ChoiceSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)

    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object(kwargs['pk'])
        serializer = ChoiceSerializer(instance=instance)
        return Response(serializer.data)

    def update(self, request, *args, **kwargs):
        instance = self.get_object(kwargs['pk'])
        serializer = ChoiceSerializer(
            instance=instance,
            data=request.data,
            partial=True
        )
        serializer.is_valid(raise_exception=True)
        serializer.update(instance, request.data)
        return Response(serializer.data)

    def delete(self, request, *args, **kwargs):
        instance = Choice.objects.get(pk=kwargs['pk'])
        instance.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

polls/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic, View
from django.utils import timezone
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import get_object_or_404, render, redirect
from .forms import RegisterForm
from .models import Choice, Question, VotedOn
import sklearn
from django.db import models


class IndexView(generic.ListView):
    """
    View showing main page (index.html)
    """
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.all()



class DetailView(generic.DetailView):
    """
    View showing one question + its answers
    """
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    """
    View shown after voting for answer
    """
    model = Question
    template_name = 'polls/results.html'


class QuestionManipulation(View):
    """
    function used for managing voting by user
    it increase vote number of answer and record that user voted in that question
    and deletion of choices from question

    Parameters:
        id of question
    """
    def post(self, request, question_id):
        question = get_object_or_404(Question, pk=question_id)
        try:
            selected_choice = question.choice_set.get(pk=request.POST['choice'])
        except (KeyError, Choice.DoesNotExist):
            return render(request, 'polls/detail.html', {
                'question': question,
                'error_message': "You didn't select a choice.",
            })
        else:
            if '_delete' in request.POST:
                selected_choice.delete()
                return HttpResponseRedirect(reverse('polls:detail', args=(question_id,)))
            selected_choice.votes += 1
            selected_choice.save()
            if request.user.is_authenticated:
                voted_on = VotedOn(user_id=request.user, question=question)
                voted_on.save()
            return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


class RegisterView(View):
    """
    function for registering new users
    """
    template_name = "polls/register.html"
    form = RegisterForm()

    def get(self, request):
        return render(request, self.template_name, {
            "form": self.form
        })

    def post(self, request):
        temp_form = RegisterForm(request.POST)
        if temp_form.is_valid():
            temp_form.save()
            return redirect("/polls")
        else:
            return render(request, self.template_name, {
                "form": self.form
            })


class LoginUser(View):
    """
    function for login
    """
    template_name = "polls/index.html"

    def get(self, request):
        return render(request, self.template_name, {
            "error_text": "Very weird error"
        })

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(request.META.get('HTTP_REFERER', '/'))
        else:
            return render(request, self.template_name, {
                "error_text": "Incorrect user name or password"
            })


class LogoutUser(View):
    """
    function for logout
    """
    def post(self, request):
        logout(request)
        return redirect(request.META.get('HTTP_REFERER', '/'))


class AddQuestion(View):
    """
    function managing adding questions to database
    """
    template_name = "polls/add_question.html"

    def get(self, request):
        return render(request, self.template_name, {
            "success": False
        })

    def post(self, request):
        success = request.POST.get('question')
        if request.user.is_authenticated:
            question = Question(question_text=success, user_id=request.user, pub_date=timezone.now())
            question.save()
        else:
            question = Question(question_text=success, pub_date=timezone.now())
            question.save()
        return render(request, self.template_name, {
            "success": success
        })


class AddChoice(View):
    """
    function managing adding answer to question
    """
    def post(self, request, question_id):
        if request.user.is_authenticated:
            choice = Choice(choice_text=request.POST.get("choice"), question=Question.objects.get(pk=question_id), user_id=request.user)
            choice.save()
        else:
            choice = Choice(choice_text=request.POST.get("choice"), question=Question.objects.get(pk=question_id))
            choice.save()
        return HttpResponseRedirect(reverse('polls:detail', args=(question_id,)))


class DeleteQuestion(View):
    """
    delete question
    """
    def post(self, question_id):
        Question.objects.get(pk=question_id).delete()
        return HttpResponseRedirect(reverse('polls:index', args=()))

polls/templates/polls/add_question.html
{% extends "polls/base.html" %}

{% block content %}
    {% if success %}
        Successfully added question: {{ success }}
    {% endif %}
    <form method="post" action="{% url 'polls:add_question' %}">
        {% csrf_token %}
        <label for="add_question">Add question</label>
        <input type="text" name="question" id="add_question" required>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

polls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Questions and Answers</title>
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
</head>
<body>
    <div id="content">
        <div id="login_content">
            {% if user.get_username %}
                User: {{ user.get_username }}
                <form action="{% url 'polls:logout' %}">
                    <button type="submit">Logout</button>
                </form>
            {% else %}
                {% if error_text %}
                    {{ error_text }}
                {% endif %}
                <form method="post" action="{% url 'polls:login' %}">
                    {% csrf_token %}
                    <label for="username">Username:</label>
                    <input type="text" name="username" id="username" required>
                    <label for="password">Password:</label>
                    <input type="password" name="password" id="password" required>
                    <button type="submit">Login</button>
                </form>
            {% endif %}
            <form action="{% url 'polls:register' %}">
                <button type="submit">Register User</button>
            </form>
            <form action="{% url 'polls:index' %}">
                <button type="submit">Return to main page</button>
            </form>
        </div>
        <div id="app_content">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</body>
</html>

polls/templates/polls/detail.html
{% extends "polls/base.html" %}
{% load polls_extras %}

{% block content %}
        <h1>{{ question.question_text }}</h1>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            <form action="{% url 'polls:question_manipulation' question.id %}" method="post">
                {% csrf_token %}
                {% if question.choice_set.all %}
                    {% if user.is_authenticated %}
                        {% for choice in question.choice_set.all %}
                            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }},
                                {% if question.user_id == user %}
                                    (user
                                    {% if choice.user_id %}
                                        {{ choice.user_id }}
                                    {% else %}
                                        Anonymus
                                    {% endif %}
                                    ),
                                {% endif %}
                            votes number: {{ choice.votes }}
                            </label><br>
                        {% endfor %}
                        {% if user|alreadyvoted:question %}
                            <input type="submit" value="Vote" name="_vote">
                        {% else %}
                            You have already voted
                        {% endif %}
                        <input type="submit" value="Delete" name="_delete">
                    {% else %}
                        {% for choice in question.choice_set.all %}
                            <li>{{ choice.choice_text }},
                                {% if question.user_id == user %}
                                    (user
                                    {% if choice.user_id %}
                                        {{ choice.user_id }}
                                    {% else %}
                                        Anonymus
                                    {% endif %}
                                    ),
                                {% endif %}
                            votes number: {{ choice.votes }}
                            </li>
                        {% endfor %}
                        {% if not user.is_authenticated %}
                            Login to vote
                        {% else %}
                            You have already voted
                        {% endif %}
                    {% endif %}
                {% else %}
                    No questions added yet
                {% endif %}
            </form>
    <br/><br/>
    <form action="{% url 'polls:add_choice' question.id %}" method="post">
        {% csrf_token %}
        <label for="choice">Add Choice</label>
        <input type="text" name="choice" id="choice" required>
        <input type="submit" value="Add Choice">
    </form>
{% endblock %}

polls/templates/polls/index.html
{% extends "polls/base.html" %}
{% load polls_extras %}

{% block content %}

    <form action="{% url 'polls:add_question' %}">
         <button type="submit">Add Question</button>
    </form>


    {% if latest_question_list %}
        <ul>
            {% if user.is_authenticated %}
                {% with your_questions=latest_question_list|questioninclude:user %}
                    Yours questions:
                    {% if your_questions %}
                        {% for question in your_questions %}
                            {% if question.user_id == user %}
                                <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
                                <form action="{% url 'polls:delete_question' question.id %}">
                                    <button type="submit">Delete question</button>
                                </form>
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        <br/>You didnt post any questions
                    {% endif %}
                    <br/>
                {% endwith %}
                {% with not_your_questions=latest_question_list|questiondontinclude:user %}
                    Other questions:
                    {% if not_your_questions %}
                        {% for question in not_your_questions %}
                            {% if question.user_id != user %}
                                <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
                            {% endif %}
                            {% if user.is_superuser %}
                                <form action="{% url 'polls:delete_question' question.id %}">
                                    <button type="submit">Delete question</button>
                                </form>
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        <br/>App have only yours questions
                    {% endif %}
                {% endwith %}
            {% else %}
                {% for question in latest_question_list %}
                    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
                {% endfor %}
            {% endif %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock %}

polls/templates/polls/register.html
{% extends "polls/base.html" %}

{% block content %}
    <h2>Sign up</h2>
    {% if form.errors %}
        {{ form.errors }}
    {% endif %}
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign up</button>
    </form>
{% endblock %}

polls/templates/polls/results.html
{% extends "polls/base.html" %}

{% block content %}
    <h1>{{ question.question_text }}</h1>
    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>
    <form action="{% url 'polls:detail' question.id %}">
        <button type="submit">Vote again?</button>
    </form>
{% endblock %}